# Generated by Django 4.2.7 on 2024-08-24 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='phonnumber',
            new_name='phonenumber',
        ),
    ]
